# Generated by Django 4.0.1 on 2022-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('region_code_who', models.CharField(default='', max_length=10)),
                ('region_name_who', models.CharField(default='', max_length=100)),
                ('country_code', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('country_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('state_code', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhoRegionInfo',
            fields=[
                ('region_code_who', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('region_name_who', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
