# Generated by Django 4.0.1 on 2022-02-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_newsarticle_region_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
