# Generated by Django 4.0.1 on 2022-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_threadsafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_link', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('tags', models.CharField(default='', max_length=400)),
                ('linkedin', models.CharField(default='', max_length=400)),
                ('behance', models.CharField(default='', max_length=400)),
                ('github', models.CharField(default='', max_length=400)),
                ('mail', models.CharField(default='', max_length=400)),
                ('image_url', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
