# Generated by Django 4.0.1 on 2022-02-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_aboutapp_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('source_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('source_description', models.CharField(default='', max_length=400)),
                ('source_url', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutapp',
            old_name='app_link',
            new_name='play_store_link',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='id',
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='about_content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
