# Generated by Django 4.0.1 on 2022-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_datasource_rename_app_link_aboutapp_play_store_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='order',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
