# Generated by Django 4.0.1 on 2022-02-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_developer_order_alter_developer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='order',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
