# Generated by Django 4.0.1 on 2022-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('who_region', models.CharField(max_length=40)),
                ('total_confirmed', models.BigIntegerField()),
                ('daily_confirmed', models.BigIntegerField()),
                ('total_deaths', models.BigIntegerField()),
                ('daily_deaths', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryTimeseries',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('total_confirmed', models.BigIntegerField()),
                ('daily_confirmed', models.BigIntegerField()),
                ('total_deaths', models.BigIntegerField()),
                ('daily_deaths', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
