# Generated by Django 4.0.1 on 2022-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_countryinfo_regioninfo_delete_regiondata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('last_updated_time', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('news_url', models.CharField(max_length=400)),
                ('news_image_url', models.CharField(max_length=400)),
                ('published_time', models.DateTimeField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
