# Generated by Django 4.0.1 on 2022-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('news_url', models.CharField(max_length=300)),
                ('news_image_url', models.CharField(max_length=300)),
                ('published_time', models.DateTimeField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
