# Generated by Django 4.0.1 on 2022-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0002_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('last_updated_time', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
