# Generated by Django 4.0.1 on 2022-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0003_generaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='authors',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
