# Generated by Django 4.0.1 on 2022-01-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0005_alter_newsarticle_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='authors',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_image_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
