# Generated by Django 4.0.1 on 2022-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0006_alter_newsarticle_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overalldata',
            name='active_changed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overalldata',
            name='current_active',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='daily_confirmed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='daily_deceased',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='daily_recovered',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='total_confirmed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='total_deceased',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='total_recovered',
            field=models.BigIntegerField(default=0),
        ),
    ]
