# Generated by Django 4.0.1 on 2022-02-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0007_overalldata_active_changed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overalldata',
            old_name='active_changed',
            new_name='daily_active',
        ),
        migrations.RenameField(
            model_name='overalldata',
            old_name='current_active',
            new_name='total_active',
        ),
    ]
