# Generated by Django 4.0.1 on 2022-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('confirmed', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
                ('deceased', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StateTimeseriesData',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('confirmed', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
                ('deceased', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
            ],
        ),
    ]
