# Generated by Django 4.0.1 on 2022-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_remove_stateinfo_latitude_remove_stateinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stateinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
