# Generated by Django 4.0.1 on 2022-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_statedata_name_alter_stateinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('confirmed', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
                ('deceased', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
            ],
        ),
    ]
